---
- name: install nginx and deploy the frontend application  
  hosts: webserver
  become: yes
  roles:
    - 'roles/nginx'


- name: Install Java on webserver and dbserver
  hosts: all
  become: yes
  roles:
    - 'roles/java'

- name: install tomcat and deploy the application on webserver
  hosts: webserver
  become: yes
  roles:
    - tomcat   

- name: install mysql , deploy and restore the database
  hosts: db
  become: yes
  vars_files:
    - "./roles/mysql/vars/info_db.yaml"
  roles:
    - 'roles/mysql' 

  
