- name: "create group {{ group_tomcat }}"
  import_tasks: create_group_tomcat.yaml

- name: "create user {{ user_tomcat }}"
  import_tasks: create_user_tomcat.yaml

- name: create working directory
  import_tasks: create_workdir.yaml

- name: download & install & configure the service tomcat
  import_tasks: download_extract_tomcat.yaml
- name: deployment of the app
  import_tasks: deploy_app.yaml
