---
- name: Installing Mysql  and dependencies
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
     - mysql-server
     - mysql-client 
     - python3-mysqldb
     - libmysqlclient-dev
  become: yes
#  notify: start_mysql
- name: enable and start mysql
  service:
    name: mysql
    state: started
    enabled: yes
