---
- name: downlaod tomcat package
  get_url:
    url: "{{ tomcat_url }}" # required. HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
    dest: "{{ tomcat_download_dest }}" # required. Absolute path of where to download the file to. If C(dest) is a directory, either the server provided filename or, if none provided, the base name of the URL on the remote server will be used. If a directory, C(force) has no effect. If C(dest) is a directory, the file will always be downloaded (regardless of the C(force) option), but replaced only if the contents changed..


- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_download_dest }}"
    dest: "{{ tomcat_folder }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: "{{ tomcat_folder }}bin"



